### ISSUE TITLE
Delete data-typo from HTML after plugin work

### ISSUE THREAD

**Issue by vaban-ru** [Grawl/posthtml-richtypo#3]
Hello! Does the plugin have the ability to remove the date attribute `data-typo` from the HTML file after the plugin has run?

**Comment by Grawl** [comment]
No, but it easy to implement. PR are welcome

**Comment by Grawl** [comment]
if anyone want to implement this, you have to add it here:

https://github.com/Grawl/posthtml-richtypo/blob/master/lib/index.js#L46

something like `delete node.attrs[attribute]`
